# Generated by Django 4.0.3 on 2022-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_events_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.CharField(default='20 April', max_length=50, verbose_name='Date '),
        ),
    ]
