# Generated by Django 4.0.3 on 2022-04-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_eventmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTestiminial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Course Testimonial',
            },
        ),
        migrations.CreateModel(
            name='CourseTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testimonial', models.TextField(default='', verbose_name='Testimonial')),
                ('name', models.CharField(default='', max_length=50, verbose_name='CLient Name')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='course.coursetestiminial')),
            ],
            options={
                'verbose_name_plural': 'Course Testimonial',
            },
        ),
    ]
