# Generated by Django 4.0.3 on 2022-03-31 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='home/videos/', verbose_name='Video')),
                ('image', models.FileField(upload_to='home/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Backgroung Image')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='Title')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Short Description')),
                ('is_show', models.BooleanField(default=False)),
                ('button_title', models.CharField(blank=True, default='Contact Us', max_length=50, verbose_name='Button Title')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Button URL')),
            ],
            options={
                'verbose_name_plural': 'Video Banner',
            },
        ),
    ]
