# Generated by Django 4.0.3 on 2022-03-31 14:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Description'),
        ),
    ]
