# Generated by Django 4.0.3 on 2022-03-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobanner',
            name='is_show',
        ),
    ]
