# Generated by Django 4.0.3 on 2022-03-31 14:50

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_videobanner_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=djrichtextfield.models.RichTextField(default='', max_length=1000, verbose_name='Description'),
        ),
    ]
