# Generated by Django 4.0.3 on 2022-03-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Description'),
        ),
    ]
