# Generated by Django 4.0.3 on 2022-03-31 15:22

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPerks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Membership Perks',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='ProfitScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='home/screenshot/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Upload Profit Screenshot')),
                ('sortable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_perks', to='pages.membershipperks')),
            ],
            options={
                'verbose_name_plural': 'Profit Screenshots',
            },
        ),
    ]
