# Generated by Django 4.0.3 on 2022-03-31 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_membershipperks_alter_about_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitscreenshots',
            name='sortable',
        ),
        migrations.AddField(
            model_name='profitscreenshots',
            name='membership_perks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.membershipperks'),
            preserve_default=False,
        ),
    ]
