# Generated by Django 4.0.3 on 2022-03-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_profitscreenshots_sortable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_points', models.CharField(default='', max_length=50, verbose_name='Key Points')),
                ('membership_perks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.membershipperks')),
            ],
            options={
                'verbose_name_plural': 'Membership Perks Key Points',
            },
        ),
    ]
