# Generated by Django 4.0.3 on 2022-04-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_featuredin_alter_keypoints_membership_perks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestiminialPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='featuredin',
            options={'verbose_name_plural': 'Fetured In'},
        ),
        migrations.AlterModelOptions(
            name='featuredinphoto',
            options={'verbose_name_plural': 'Image'},
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testimonial', models.TextField(default='', verbose_name='Testimonial')),
                ('name', models.CharField(default='', max_length=50, verbose_name='CLient Name')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='pages.testiminialpass')),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
    ]
