# Generated by Django 4.0.3 on 2022-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_recommendedbooks_bookimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedbooks',
            options={'verbose_name_plural': 'Recommend Book'},
        ),
        migrations.RemoveField(
            model_name='recommendedbooks',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='recommendedbooks',
            name='url',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book_name',
            field=models.CharField(default='', max_length=100, verbose_name='Book Name'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Book URL'),
        ),
    ]
