# Generated by Django 4.0.3 on 2022-04-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_recommendedbooks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookimage',
            options={'verbose_name_plural': 'Book'},
        ),
    ]
