# Generated by Django 4.0.3 on 2022-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_introvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premium_clients', models.CharField(default='', max_length=100, verbose_name='Premium Client')),
                ('premium_clients_users', models.IntegerField(default='', verbose_name='Total Users')),
                ('international_clients', models.CharField(default='', max_length=100, verbose_name='International Client')),
                ('international_clients_users', models.IntegerField(default='', verbose_name='Total Users')),
                ('subscriber', models.CharField(default='', max_length=100, verbose_name='Subscriber Client')),
                ('subscriber_users', models.IntegerField(default='', verbose_name='Total Users')),
            ],
            options={
                'verbose_name': 'Intro Video',
            },
        ),
    ]
