# Generated by Django 4.0.3 on 2022-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='international_clients',
            field=models.CharField(default='International Client', max_length=100, verbose_name='International Client'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='premium_clients',
            field=models.CharField(default='Premium Client', max_length=100, verbose_name='Premium Client'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber',
            field=models.CharField(default='Subscriber Client', max_length=100, verbose_name='Subscriber Client'),
        ),
    ]
