# Generated by Django 4.0.3 on 2022-04-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredin',
            name='message',
        ),
    ]
