# Generated by Django 4.0.3 on 2022-04-01 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='Title')),
                ('image', models.FileField(upload_to='about/banner', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Banner Image | 1280x1280')),
            ],
            options={
                'verbose_name': 'Banner Image',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_one_title', models.CharField(default='', max_length=50, verbose_name='Step One Title')),
                ('step_one_description', models.TextField(max_length=500, verbose_name='Step One Description')),
                ('step_two_title', models.CharField(default='', max_length=50, verbose_name='Step Two Title')),
                ('step_two_description', models.TextField(max_length=500, verbose_name='Step Two Description')),
                ('step_three_description', models.TextField(max_length=500, verbose_name='Step Three Description')),
                ('step_three_title', models.CharField(default='', max_length=50, verbose_name='Step Three Title')),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
            },
        ),
    ]
