# Generated by Django 4.0.3 on 2022-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_faq_faqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=10000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'What We Do',
            },
        ),
    ]
