# Generated by Django 4.0.3 on 2022-04-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_whatwedo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name_plural': 'What We Do'},
        ),
    ]
