# Generated by Django 4.0.3 on 2022-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TawkToChatCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.CharField(max_length=255, verbose_name='Site ID')),
                ('widget_id', models.CharField(max_length=255, verbose_name='Widget ID')),
            ],
            options={
                'verbose_name_plural': 'Tawk To Chat Credential',
            },
        ),
    ]
